// Hand-authored classification of each reference-catalog hint against the squirrelscan rule set.
// status: COVERED | PARTIAL | MISSING | SKIP
// Used by map-hints.mjs to emit reports/hints-mapping.json and PRD tables.
export const MAPPING = {
  // ===================== INDEXABILITY (50) =====================
  'canonical-outside-of-head': { status: 'COVERED', rules: ['core-canonical-outside-head'] },
  'canonical-points-to-http-version': { status: 'COVERED', rules: ['core-canonical-http-mismatch'] },
  'disallowed-javascript-file': { status: 'COVERED', rules: ['crawl-blocked-resources', 'js-blocked-resources'] },
  'disallowed-image': { status: 'MISSING', note: 'crawl-blocked-resources covers CSS/JS only, not image URLs.', ruleId: 'crawl-blocked-images', cat: 'crawl', effort: 'medium', data: 'robots.txt (already fetched) + image URL list' },
  'disallowed-style-sheet': { status: 'COVERED', rules: ['crawl-blocked-resources'] },
  'head-contains-a-noscript-tag-which-includes-an-image': { status: 'COVERED', rules: ['htmlval-noscript-in-head'], note: 'Rule flags any non-link/style/meta content in head noscript, which includes img.' },
  'head-contains-invalid-html-elements': { status: 'COVERED', rules: ['htmlval-invalid-head'] },
  'meta-robots-found-outside-of-head': { status: 'COVERED', rules: ['content-meta-in-body'] },
  'canonical-contains-invalid-html-attributes': { status: 'COVERED', rules: ['core-canonical-attributes'] },
  'html-file-size-exceeds-googles-2mb-limit': { status: 'COVERED', rules: ['htmlval-size-limit'] },
  'mismatched-canonical-tag-in-html-and-http-header': { status: 'COVERED', rules: ['core-canonical-conflicting', 'core-canonical-header'] },
  'multiple-mismatched-canonical-tags': { status: 'COVERED', rules: ['core-canonical-conflicting', 'core-canonical-multiple'] },
  'canonical-is-malformed-or-empty': { status: 'COVERED', rules: ['core-canonical-valid'] },
  'canonical-points-to-https-version': { status: 'COVERED', rules: ['core-canonical-http-mismatch'] },
  'canonical-points-to-another-canonicalized-url': { status: 'COVERED', rules: ['crawl-canonical-chain'], note: 'Crawl mode only: follows the canonical chain via SiteContext.pages; warns when the target is itself canonicalized elsewhere.' },
  'canonical-loop': { status: 'COVERED', rules: ['core-canonical-loop', 'crawl-canonical-loop'], note: 'crawl-canonical-loop detects true A↔B loops from the crawl-level canonical map; core-canonical-loop keeps the single-page heuristic.' },
  'canonical-points-to-a-disallowed-url': { status: 'COVERED', rules: ['crawl-canonical-to-disallowed'], note: 'Crawl mode only: cross-references the canonical target against the per-URL robots.txt disallow flags.' },
  'canonicalized-url-is-noindex-nofollow': { status: 'COVERED', rules: ['core-canonical-to-noindex'] },
  'canonical-points-to-a-noindex-url': { status: 'COVERED', rules: ['crawl-canonical-to-noindex'], note: 'Crawl mode only: reads the canonical target\'s robots state from SiteContext.pages.' },
  'canonical-points-to-a-url-that-is-error-5xx': { status: 'COVERED', rules: ['crawl-canonical-redirect'], note: 'Rule HEAD-fetches the canonical target and fails on >=400.' },
  'canonical-points-to-a-url-that-is-not-found-404': { status: 'COVERED', rules: ['crawl-canonical-redirect'] },
  'mismatched-nofollow-directives-in-html-and-header': { status: 'COVERED', rules: ['core-robots-meta', 'core-robots-directive-mismatch'] },
  'mismatched-noindex-directives-in-html-and-header': { status: 'COVERED', rules: ['core-robots-meta', 'core-robots-directive-mismatch'] },
  'url-contains-a-form-with-a-get-method': { status: 'COVERED', rules: ['technical-form-get-method'] },
  'canonical-only-found-in-rendered-dom': { status: 'COVERED', rules: ['js-canonical-mismatch', 'js-rendered-canonical'] },
  'rendered-canonical-is-different-to-html-source': { status: 'COVERED', rules: ['js-canonical-mismatch'] },
  'isolated-url-only-found-via-a-canonical': { status: 'COVERED', rules: ['crawl-isolated-url'], note: 'Crawl mode only: per-URL discovery sources (link/canonical/redirect/sitemap/entry) recorded during the crawl.' },
  'isolated-url-only-found-via-a-redirect': { status: 'COVERED', rules: ['crawl-isolated-url'], note: 'Same rule; redirect-only discovery is one of the isolation forms it reports.' },
  'isolated-url-only-found-via-a-noindex-follow': { status: 'COVERED', rules: ['crawl-isolated-url'], note: 'Same rule; fails when every linking page is noindex,follow.' },
  'isolated-url-only-linked-from-other-isolated-urls': { status: 'COVERED', rules: ['crawl-isolated-url'], note: 'Same rule; one propagation pass over the isolated set catches URLs linked only from isolated pages.' },
  'canonical-contains-superfluous-html-attributes': { status: 'COVERED', rules: ['core-canonical-attributes'] },
  'canonical-is-a-relative-url': { status: 'COVERED', rules: ['core-canonical-valid'] },
  'canonical-points-to-a-redirecting-url': { status: 'COVERED', rules: ['crawl-canonical-redirect'] },
  'multiple-nofollow-directives': { status: 'COVERED', rules: ['core-robots-meta', 'core-robots-directive-mismatch'] },
  'multiple-noindex-directives': { status: 'COVERED', rules: ['core-robots-meta', 'core-robots-directive-mismatch'] },
  'noindex-in-html-and-http-header': { status: 'COVERED', rules: ['core-robots-meta', 'core-robots-directive-mismatch'] },
  'nofollow-in-html-and-http-header': { status: 'COVERED', rules: ['core-robots-meta', 'core-robots-directive-mismatch'] },
  'canonical-points-to-homepage': { status: 'COVERED', rules: ['core-canonical-to-homepage'] },
  'contains-possible-soft-404-phrases': { status: 'COVERED', rules: ['technical-soft-404'] },
  'canonical-tag-in-html-and-http-header': { status: 'COVERED', rules: ['core-canonical-header'] },
  'multiple-canonical-tags': { status: 'COVERED', rules: ['core-canonical-conflicting', 'core-canonical-multiple'] },
  'base-url-malformed-or-empty': { status: 'COVERED', rules: ['htmlval-base-url'] },
  'multiple-mismatched-base-urls': { status: 'COVERED', rules: ['htmlval-base-url'] },
  'multiple-base-urls': { status: 'COVERED', rules: ['htmlval-base-url'] },
  'canonical-points-to-a-different-internal-url': { status: 'PARTIAL', rules: ['core-canonical-loop'], note: 'Insight only: canonicalization is detected but never surfaced as neutral information.' },
  'canonical-points-to-external-url': { status: 'COVERED', rules: ['core-canonical-external'], note: 'Insight-level rule: always passes, reports cross-domain canonicals for confirmation.' },
  'has-noindex-and-nofollow-directives': { status: 'COVERED', rules: ['core-robots-meta'] },
  'internal-disallowed-urls': { status: 'PARTIAL', rules: ['crawl-indexability-conflict'], note: 'Conflict (disallowed + noindex) is detected; a URL that is simply disallowed is not surfaced as an insight.' },
  'url-only-has-nofollow-incoming-internal-links': { status: 'COVERED', rules: ['links-inbound-all-nofollow'], note: 'Crawl mode only: per-edge nofollow state from SiteContext.inboundEdgesByUrl; warns at most (insight-level).' },
  'head-contains-a-noscript-tag': { status: 'PARTIAL', rules: ['htmlval-noscript-in-head'], note: 'We only flag invalid noscript contents; bare presence (insight) is not reported.' },

  // ===================== LINKS (18) =====================
  'has-link-with-a-url-referencing-localhost-or-127001': { status: 'COVERED', rules: ['links-localhost'] },
  'has-link-with-a-url-referencing-a-local-or-unc-file-path': { status: 'COVERED', rules: ['links-local-file'] },
  'has-a-link-with-whitespace-in-href-attribute': { status: 'COVERED', rules: ['links-whitespace-href'] },
  'has-no-outgoing-links': { status: 'COVERED', rules: ['links-dead-end-pages'], note: 'Superset: we flag pages with no outgoing internal links, which includes pages with no outgoing links at all.' },
  'has-only-one-followed-internal-linking-url': { status: 'COVERED', rules: ['links-orphan-pages'], note: 'Rule explicitly warns at inboundCount === 1 in crawl mode.' },
  'has-outgoing-links-with-malformed-href-data': { status: 'COVERED', rules: ['links-invalid'] },
  'url-is-orphaned-and-was-not-found-by-the-crawler': { status: 'COVERED', rules: ['crawl-sitemap-orphan-urls', 'links-orphan-pages'] },
  'has-link-to-a-non-http-protocol': { status: 'COVERED', rules: ['links-non-http-protocol'] },
  'pagination-url-has-no-incoming-internal-links': { status: 'COVERED', rules: ['crawl-pagination-orphaned', 'crawl-pagination-isolated'], note: 'crawl-pagination-isolated checks inbound anchors for paginated URLs (crawl mode only).' },
  'only-receives-nofollow-links-or-links-from-canonicalized-urls': { status: 'COVERED', rules: ['links-inbound-low-quality'], note: 'Crawl mode only: warns when no inbound edge passes link equity (all nofollow or from canonicalized-away pages).' },
  'has-an-internal-link-with-no-anchor-text': { status: 'COVERED', rules: ['a11y-link-text', 'links-anchor-text'] },
  'has-an-anchored-image-with-no-alt-text': { status: 'COVERED', rules: ['images-alt-present'] },
  'url-receives-both-follow-nofollow-internal-links': { status: 'COVERED', rules: ['links-inbound-mixed-follow'], note: 'Crawl mode only: per-edge nofollow state from SiteContext.inboundEdgesByUrl.' },
  'has-incoming-followed-links-that-do-not-use-descriptive-anchor-text': { status: 'COVERED', rules: ['links-inbound-anchor-text'], note: 'Crawl mode only: per-edge anchor text from SiteContext.inboundEdgesByUrl; warns when every followed inbound link is generic.' },
  'has-one-or-more-outgoing-followed-links-with-non-descriptive-anchor-text': { status: 'COVERED', rules: ['links-anchor-text'] },
  'has-a-link-with-an-empty-href-attribute': { status: 'COVERED', rules: ['links-invalid'] },
  'has-broken-bookmarks': { status: 'COVERED', rules: ['links-broken-fragment'] },
  'has-link-with-a-url-in-onclick-attribute': { status: 'COVERED', rules: ['links-onclick'] },

  // ===================== ON-PAGE (22) =====================
  'title-tag-is-missing': { status: 'COVERED', rules: ['core-title-present'] },
  'html-is-missing-or-empty': { status: 'COVERED', rules: ['technical-empty-html'] },
  'title-tag-is-empty': { status: 'COVERED', rules: ['core-title-present'], note: 'Explicitly fails on present-but-empty title.' },
  'title-tag-outside-of-head': { status: 'COVERED', rules: ['htmlval-title-outside-head'] },
  'broken-or-invalid-html': { status: 'COVERED', rules: ['content-broken-html'] },
  'multiple-title-tags': { status: 'COVERED', rules: ['htmlval-multiple-titles'] },
  'meta-description-outside-of-head': { status: 'COVERED', rules: ['content-meta-in-body'] },
  'h1-tag-is-missing': { status: 'COVERED', rules: ['core-h1-present'] },
  'h1-tag-is-empty': { status: 'COVERED', rules: ['core-h1-present'], note: 'Explicitly fails on present-but-empty H1.' },
  'images-with-missing-alt-text': { status: 'COVERED', rules: ['images-alt-present'] },
  'contains-lorem-ipsum-dummy-text': { status: 'COVERED', rules: ['htmlval-lorem-ipsum'] },
  'h1-length-too-short': { status: 'COVERED', rules: ['content-heading-length'] },
  'h1-length-too-long': { status: 'COVERED', rules: ['content-heading-length'] },
  'title-tag-length-too-short': { status: 'COVERED', rules: ['core-title-length', 'content-title-pixel-width'] },
  'title-tag-length-too-long': { status: 'COVERED', rules: ['core-title-length', 'content-title-pixel-width'] },
  'meta-description-length-too-short': { status: 'COVERED', rules: ['core-description-length', 'content-description-pixel-width'] },
  'meta-description-length-too-long': { status: 'COVERED', rules: ['core-description-length', 'content-description-pixel-width'] },
  'meta-description-is-empty': { status: 'COVERED', rules: ['core-description-present', 'core-description-length'] },
  'multiple-meta-descriptions': { status: 'COVERED', rules: ['htmlval-multiple-descriptions'] },
  'multiple-h1-tags': { status: 'COVERED', rules: ['core-h1-single'] },
  'title-and-meta-description-are-the-same': { status: 'COVERED', rules: ['content-title-same-as-description'] },
  'meta-description-is-missing': { status: 'COVERED', rules: ['core-description-present'] },

  // ===================== REDIRECTS (13) =====================
  'internal-url-redirect-broken-4xx-or-5xx': { status: 'COVERED', rules: ['redirect-broken'] },
  'internal-url-redirects-back-to-itself': { status: 'COVERED', rules: ['redirect-loop'] },
  'external-url-redirect-broken-4xx-or-5xx': { status: 'COVERED', rules: ['links-external-valid', 'redirect-resource-broken'], note: 'redirect-resource-broken fails on redirected resources (incl. external) ending 4xx/5xx; needs rendered asset data (not measured under --no-cwv).' },
  'resource-url-redirect-broken-4xx-or-5xx': { status: 'COVERED', rules: ['js-failed-requests', 'redirect-resource-broken'], note: 'Per-resource redirect chains from the Playwright render; not measured under --no-cwv.' },
  'page-resource-url-redirects-back-to-itself': { status: 'COVERED', rules: ['redirect-resource-loop'], note: 'Per-resource redirect loop detection from the rendered asset data; not measured under --no-cwv.' },
  'page-resource-url-is-part-of-a-chained-redirect-loop': { status: 'COVERED', rules: ['redirect-resource-loop'], note: 'Same rule; any loop back to a URL already in the chain is detected.' },
  'internal-url-is-part-of-a-chained-redirect-loop': { status: 'COVERED', rules: ['redirect-loop'] },
  'internal-redirects-from-trailing-slash-mismatch': { status: 'COVERED', rules: ['technical-trailing-slash', 'links-redirect-chains'] },
  'internal-redirects-from-case-normalization': { status: 'COVERED', rules: ['redirect-case-normalization'] },
  'internal-redirected-urls': { status: 'COVERED', rules: ['links-redirect-chains'] },
  'redirected-page-resource-urls': { status: 'COVERED', rules: ['redirect-resource', 'redirect-resource-chain'], note: 'redirect-resource-chain warns on multi-hop resource chains from the rendered asset data; not measured under --no-cwv.' },
  'external-redirected-urls': { status: 'PARTIAL', rules: ['links-external-valid'], note: 'Insight-level; external redirects are traversed but not reported as such.' },
  'redirects-using-a-meta-refresh': { status: 'COVERED', rules: ['redirect-meta-refresh', 'redirect-http-refresh'] },

  // ===================== INTERNAL (18) =====================
  'broken-internal-urls': { status: 'COVERED', rules: ['links-broken-internal', 'technical-server-error'] },
  'url-contains-upper-case-characters': { status: 'COVERED', rules: ['url-uppercase'] },
  'url-contains-whitespace': { status: 'COVERED', rules: ['url-spaces'] },
  'query-string-contains-session-id-parameters': { status: 'COVERED', rules: ['url-session-ids'] },
  'query-string-contains-tracking-parameters': { status: 'COVERED', rules: ['url-tracking-params'] },
  'query-string-contains-a-question-mark': { status: 'COVERED', rules: ['url-parameters'] },
  'query-string-contains-repetitive-parameters': { status: 'COVERED', rules: ['url-parameters'] },
  'url-contains-a-double-slash': { status: 'COVERED', rules: ['url-double-slash'] },
  'url-contains-non-ascii-characters': { status: 'COVERED', rules: ['url-non-ascii'] },
  'url-contains-repetitive-elements': { status: 'COVERED', rules: ['url-repetitive-path'] },
  'url-contains-more-than-one-google-tag-manager-code': { status: 'COVERED', rules: ['technical-duplicate-gtm'] },
  'url-contains-more-than-one-google-analytics-code': { status: 'COVERED', rules: ['technical-duplicate-ga'] },
  'query-string-contains-more-than-three-parameters': { status: 'COVERED', rules: ['url-parameters'] },
  'query-string-contains-paginated-parameters': { status: 'PARTIAL', rules: ['url-parameters', 'crawl-pagination-sequence'], note: 'Pagination via rel=next/prev is checked; param-based pagination (?page=2) is not identified as such.' },
  'query-string-contains-search-or-filter-parameters': { status: 'PARTIAL', rules: ['url-internal-search'], note: 'Internal search URLs are detected; filter parameters are not.' },
  'query-string-contains-sort-parameters': { status: 'PARTIAL', rules: ['url-parameters'], note: 'Insight-level; sort params counted but not classified.' },
  'url-contains-no-google-tag-manager-code': { status: 'SKIP', note: 'Analytics presence is not an SEO issue; deliberately out of scope.' },
  'url-contains-no-google-analytics-code': { status: 'SKIP', note: 'Same as above.' },

  // ===================== SEARCH-TRAFFIC (8) =====================
  'canonicalized-url-received-organic-search-traffic': { status: 'SKIP', note: 'Requires Google Search Console / GA4 integration, which the CLI does not have.' },
  'disallowed-url-received-organic-search-traffic': { status: 'SKIP', note: 'Requires GSC/GA4.' },
  'forbidden-403-url-received-search-traffic': { status: 'SKIP', note: 'Requires GSC/GA4.' },
  'noindex-url-received-organic-search-traffic': { status: 'SKIP', note: 'Requires GSC/GA4.' },
  'not-found-4xx-url-received-search-traffic': { status: 'SKIP', note: 'Requires GSC/GA4.' },
  'redirect-3xx-url-received-organic-search-traffic': { status: 'SKIP', note: 'Requires GSC/GA4.' },
  'orphan-url-received-search-traffic': { status: 'SKIP', note: 'Requires GSC/GA4.' },
  'had-bounce-rate-greater-than-or-equal-to-80': { status: 'SKIP', note: 'Requires GA4. GA4 also no longer reports bounce rate in this form.' },

  // ===================== XML-SITEMAPS (9) =====================
  'error-5xx-url-in-xml-sitemaps': { status: 'COVERED', rules: ['crawl-sitemap-non-200'], note: 'Crawl mode only: sitemap URLs cross-referenced with crawled status codes.' },
  'noindex-url-in-xml-sitemaps': { status: 'COVERED', rules: ['crawl-noindex-in-sitemap'] },
  'not-found-4xx-url-in-xml-sitemaps': { status: 'COVERED', rules: ['crawl-sitemap-non-200'] },
  'canonicalized-url-in-xml-sitemaps': { status: 'COVERED', rules: ['crawl-sitemap-non-canonical'], note: 'Crawl mode only: canonical state per sitemap URL.' },
  'disallowed-url-in-xml-sitemaps': { status: 'COVERED', rules: ['crawl-sitemap-disallowed'], note: 'Crawl mode only: per-URL robots.txt disallow flags from the crawl.' },
  'forbidden-403-url-in-xml-sitemaps': { status: 'COVERED', rules: ['crawl-sitemap-non-200'] },
  'redirect-3xx-url-in-xml-sitemaps': { status: 'COVERED', rules: ['crawl-sitemap-non-200'], note: '3xx sitemap URLs warn rather than fail.' },
  'timed-out-url-in-xml-sitemaps': { status: 'COVERED', rules: ['crawl-sitemap-non-200'], note: 'Timeouts (statusCode 0) warn rather than fail.' },
  'url-in-multiple-xml-sitemaps': { status: 'COVERED', rules: ['crawl-sitemap-duplicate-urls', 'crawl-sitemap-cross-duplicates'], note: 'Within-document duplicates and cross-sitemap membership both checked.' },

  // ===================== SECURITY (6) =====================
  'mixed-content-loads-http-resources-on-https-url': { status: 'COVERED', rules: ['security-mixed-content'] },
  'internal-http-urls': { status: 'COVERED', rules: ['security-https', 'security-https-redirect'] },
  'https-url-links-to-an-http-url': { status: 'COVERED', rules: ['links-https-downgrade'] },
  'http-url-contains-a-password-input-field': { status: 'COVERED', rules: ['security-password-http'] },
  'https-url-contains-a-form-posting-to-http': { status: 'COVERED', rules: ['security-form-https'] },
  'loads-page-resources-using-protocol-relative-uris': { status: 'COVERED', rules: ['security-protocol-relative'] },

  // ===================== INTERNATIONAL (25) =====================
  'invalid-incoming-hreflang-annotations': { status: 'COVERED', rules: ['i18n-hreflang', 'i18n-hreflang-incoming-invalid'], note: 'Crawl mode only for the incoming side: annotations from other crawled pages targeting this URL are code-validated.' },
  'has-invalid-outgoing-hreflang-annotations': { status: 'COVERED', rules: ['i18n-hreflang'], note: 'Language/region codes are validated against ISO 639-1 / 3166-1.' },
  'has-outgoing-hreflang-annotations-to-noindex-urls': { status: 'COVERED', rules: ['crawl-hreflang-to-noindex'], note: 'Crawl mode only: reads hreflang target robots state from SiteContext.pages.' },
  'noindex-url-has-incoming-hreflang': { status: 'COVERED', rules: ['i18n-hreflang-to-noindex'] },
  'has-outgoing-hreflang-annotations-to-broken-urls': { status: 'COVERED', rules: ['i18n-hreflang-to-broken'], note: 'Static malformed-URL checks plus crawl-mode live check: 4xx/5xx fail, fetch timeouts warn.' },
  'has-outgoing-hreflang-annotations-to-canonicalized-urls': { status: 'COVERED', rules: ['i18n-hreflang-to-non-canonical'] },
  'canonicalized-url-has-incoming-hreflang': { status: 'PARTIAL', rules: ['i18n-hreflang-to-non-canonical'], note: 'Outgoing direction covered; "this page is canonicalized and is an hreflang target" needs crawl-level data.' },
  'has-outgoing-hreflang-annotations-to-disallowed-urls': { status: 'COVERED', rules: ['crawl-hreflang-to-disallowed'], note: 'Crawl mode only: cross-references hreflang targets against robots.txt disallows.' },
  'disallowed-url-has-incoming-hreflang': { status: 'COVERED', rules: ['crawl-hreflang-disallowed-target'], note: 'Crawl mode only: checks the site-wide hreflang graph against this page\'s disallow flag.' },
  'has-conflicting-incoming-hreflang-annotations': { status: 'COVERED', rules: ['crawl-hreflang-incoming-conflict'], note: 'Crawl mode only: compares what other crawled pages say about this URL; x-default excluded.' },
  'has-conflicting-outgoing-hreflang-annotations': { status: 'COVERED', rules: ['i18n-hreflang-conflicting'] },
  'has-multiple-self-referencing-hreflang-annotations': { status: 'COVERED', rules: ['i18n-hreflang-return-links', 'i18n-hreflang-conflicting'] },
  'has-outgoing-hreflang-annotation-to-multiple-urls': { status: 'COVERED', rules: ['i18n-hreflang-conflicting'] },
  'has-outgoing-hreflang-annotations-using-relative-urls': { status: 'COVERED', rules: ['i18n-hreflang-relative-url'] },
  'invalid-html-lang-attribute': { status: 'COVERED', rules: ['i18n-lang-attribute'] },
  'mismatched-hreflang-and-html-lang-declarations': { status: 'COVERED', rules: ['i18n-hreflang-lang-mismatch'] },
  'missing-hreflang-annotations': { status: 'PARTIAL', rules: ['i18n-hreflang'], note: 'Presence is checked, but we do not infer that a site should have hreflang (multilingual signals).' },
  'missing-reciprocal-hreflang-no-return-tag': { status: 'COVERED', rules: ['i18n-hreflang-return-links', 'crawl-hreflang-reciprocity'], note: 'Crawl mode only for true reciprocity: crawled targets must annotate this page in return; uncrawled targets skipped.' },
  'has-outgoing-hreflang-annotations-to-redirecting-urls': { status: 'COVERED', rules: ['i18n-hreflang-to-redirect'], note: 'HTTP-on-HTTPS heuristic plus crawl-mode live check for actual 3xx responses.' },
  'has-unsupported-or-misconfigured-hreflang': { status: 'COVERED', rules: ['i18n-hreflang'] },
  'has-hreflang-annotations-using-multiple-methods': { status: 'COVERED', rules: ['i18n-hreflang-multiple-methods'], note: 'HTML vs HTTP header covered; XML sitemap method not parsed.' },
  'missing-canonical-url': { status: 'COVERED', rules: ['core-canonical-present'] },
  'missing-html-lang-attribute': { status: 'COVERED', rules: ['i18n-lang-attribute'] },
  'has-hreflang-annotations-without-html-lang': { status: 'COVERED', rules: ['i18n-lang-attribute', 'i18n-hreflang-lang-mismatch'] },
  'hreflang-annotation-also-x-default': { status: 'COVERED', rules: ['i18n-hreflang-x-default'] },

  // ===================== AMP (19) =====================
  'amp-page-has-validation-errors': { status: 'SKIP', note: 'AMP is deprecated as a ranking concern (page experience update 2021+; Google killed AMP cache requirement). Recommend not implementing.' },
  'amp-page-url-has-canonical-url-which-is-error-5xx': { status: 'SKIP', note: 'AMP-specific; see amp-page-has-validation-errors.' },
  'amp-page-url-has-canonical-url-which-is-forbidden-403': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-has-canonical-url-which-is-not-found-4xx': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-is-error-5xx': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-is-forbidden-403': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-is-not-found-4xx': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-has-canonical-url-which-is-canonicalized': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-has-canonical-url-which-is-disallowed': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-has-canonical-url-which-is-noindex': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-has-canonical-url-which-is-not-indexable': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-has-canonical-url-which-is-redirect-3xx': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-is-disallowed': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-is-missing-a-canonical-tag': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-is-missing-the-html-amp-tag': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-is-noindex': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-is-redirect-3xx': { status: 'SKIP', note: 'AMP-specific.' },
  'amphtml-link-only-found-in-rendered-dom': { status: 'SKIP', note: 'AMP-specific.' },
  'amp-page-url-loops': { status: 'SKIP', note: 'AMP-specific.' },

  // ===================== DUPLICATE-CONTENT (7) =====================
  'urls-with-duplicate-content': { status: 'COVERED', rules: ['content-duplicate-exact'] },
  'urls-with-duplicate-page-titles': { status: 'COVERED', rules: ['core-title-unique'] },
  'technically-duplicate-urls': { status: 'PARTIAL', rules: ['url-uppercase', 'url-parameters', 'redirect-case-normalization'], note: 'We check the individual URL properties but do not cluster URLs that resolve to identical content.' },
  'urls-with-duplicate-title-and-meta-descriptions': { status: 'COVERED', rules: ['core-title-unique', 'content-duplicate-description'], note: 'The combination is implied by the two single-field rules.' },
  'urls-with-similar-content': { status: 'COVERED', rules: ['content-duplicate-near'] },
  'urls-with-duplicate-h1s': { status: 'COVERED', rules: ['content-duplicate-h1'], note: 'Crawl mode only: compares H1 text across SiteContext.pages.' },
  'urls-with-duplicate-meta-descriptions': { status: 'COVERED', rules: ['content-duplicate-description'] },

  // ===================== MOBILE-FRIENDLY (13) =====================
  'multiple-viewport-meta-tags-were-found-in-the-head': { status: 'COVERED', rules: ['mobile-multiple-viewports'] },
  'content-does-not-size-correctly-to-viewport': { status: 'PARTIAL', rules: ['mobile-viewport-width', 'mobile-horizontal-scroll'], note: 'Static heuristics only; a true rendered-viewport overflow measurement would need a mobile render pass.' },
  'font-size-is-too-small-for-mobile-devices': { status: 'COVERED', rules: ['mobile-font-size'] },
  'has-one-or-more-image-map-map-tags': { status: 'COVERED', rules: ['mobile-image-maps'] },
  'tap-targets-are-too-small-and-close': { status: 'COVERED', rules: ['a11y-touch-targets'] },
  'missing-viewport-meta-tag-in-the-head': { status: 'COVERED', rules: ['core-viewport-present'] },
  'the-viewport-meta-tag-does-not-have-a-width-set': { status: 'COVERED', rules: ['mobile-viewport-content'] },
  'the-viewport-meta-tag-has-a-specific-width-set': { status: 'COVERED', rules: ['mobile-viewport-width'] },
  'the-viewport-meta-tag-has-a-maximum-scale-set': { status: 'COVERED', rules: ['a11y-zoom-disabled'] },
  'the-viewport-meta-tag-has-a-minimum-scale-set': { status: 'COVERED', rules: ['a11y-zoom-disabled', 'mobile-viewport-content'] },
  'the-viewport-meta-tag-initial-scale-is-incorrect': { status: 'COVERED', rules: ['mobile-viewport-content'] },
  'the-viewport-meta-tag-is-missing-an-initial-scale': { status: 'COVERED', rules: ['mobile-viewport-content'] },
  'the-viewport-meta-tag-prevents-the-user-from-scaling': { status: 'COVERED', rules: ['a11y-zoom-disabled'] },

  // ===================== PERFORMANCE (20) =====================
  'eliminate-render-blocking-resources': { status: 'COVERED', rules: ['perf-render-blocking'] },
  'avoid-enormous-network-payloads': { status: 'COVERED', rules: ['perf-page-weight'] },
  'serve-static-assets-with-an-efficient-cache-policy': { status: 'COVERED', rules: ['perf-cache-policy', 'perf-asset-cache-policy'], note: 'Per-asset cache headers from the Playwright render; not measured under --no-cwv.' },
  'efficiently-encode-images': { status: 'COVERED', rules: ['images-size', 'images-modern-format', 'perf-image-encoding'], note: 'perf-image-encoding measures transferred bytes per rendered image; not measured under --no-cwv.' },
  'defer-offscreen-images': { status: 'COVERED', rules: ['images-lazy-loading', 'perf-lazy-above-fold'] },
  'minify-javascript': { status: 'COVERED', rules: ['perf-minify-js'], note: 'Inline JS checked directly; large external scripts without a .min. URL marker flagged heuristically from render asset data (bodies not captured).' },
  'minify-css': { status: 'COVERED', rules: ['perf-minify-css'], note: 'Inline CSS checked directly; large external stylesheets without a .min. URL marker flagged heuristically from render asset data (bodies not captured).' },
  'reduce-server-response-times-ttfb': { status: 'COVERED', rules: ['cwv-ttfb', 'perf-response-time'] },
  'enable-text-compression': { status: 'COVERED', rules: ['perf-text-compression', 'perf-brotli', 'perf-asset-compression'], note: 'perf-asset-compression checks sub-resource compression from render asset data; not measured under --no-cwv.' },
  'ensure-text-remains-visible-during-webfont-load': { status: 'COVERED', rules: ['perf-font-loading'] },
  'add-dimensions-to-images': { status: 'COVERED', rules: ['images-dimensions'] },
  'properly-size-images': { status: 'PARTIAL', rules: ['images-responsive', 'images-size'], note: 'Rendered-size vs intrinsic-size comparison needs layout measurement.', ruleId: 'perf-image-oversize', cat: 'perf', effort: 'complex', data: 'rendered layout measurements' },
  'remove-unused-css': { status: 'MISSING', note: 'Needs CSS coverage collection; planned as perf-unused-css in the Lighthouse PRD Phase 3 but not yet implemented.', ruleId: 'perf-unused-css', cat: 'perf', effort: 'complex', data: 'Playwright coverage API' },
  'remove-unused-javascript': { status: 'MISSING', note: 'Needs JS coverage collection; planned as perf-unused-js in the Lighthouse PRD Phase 3 but not yet implemented.', ruleId: 'perf-unused-js', cat: 'perf', effort: 'complex', data: 'Playwright coverage API' },
  'transferred-image-size-is-over-100kb': { status: 'COVERED', rules: ['images-size', 'perf-image-encoding'], note: 'perf-image-encoding measures content-length per rendered image against a 100KB threshold; not measured under --no-cwv.' },
  'serve-images-in-next-gen-formats': { status: 'COVERED', rules: ['images-modern-format'] },
  'use-video-formats-for-animated-content': { status: 'COVERED', rules: ['perf-video-for-animations'] },
  'avoid-excessive-dom-width': { status: 'COVERED', rules: ['perf-dom-size'] },
  'avoid-excessive-dom-size': { status: 'COVERED', rules: ['perf-dom-size'] },
  'avoid-excessive-dom-depth': { status: 'COVERED', rules: ['perf-dom-size'] },

  // ===================== RENDERED (12) =====================
  'noindex-only-in-the-http-response-html': { status: 'COVERED', rules: ['js-noindex-mismatch'] },
  'nofollow-only-in-the-http-response-html': { status: 'COVERED', rules: ['js-noindex-mismatch'] },
  'canonical-only-in-the-rendered-html': { status: 'COVERED', rules: ['js-canonical-mismatch', 'js-rendered-canonical'] },
  'canonical-mismatch-between-rendered-and-response-html': { status: 'COVERED', rules: ['js-canonical-mismatch'] },
  'page-title-only-in-the-rendered-html': { status: 'COVERED', rules: ['js-rendered-title', 'js-title-modified'] },
  'page-title-modified-by-javascript': { status: 'COVERED', rules: ['js-title-modified'] },
  'meta-description-only-in-the-rendered-html': { status: 'COVERED', rules: ['js-rendered-description', 'js-description-modified'] },
  'meta-description-modified-by-javascript': { status: 'COVERED', rules: ['js-description-modified'] },
  'h1-only-in-the-rendered-html': { status: 'COVERED', rules: ['js-rendered-h1', 'js-h1-modified'] },
  'h1-modified-by-javascript': { status: 'COVERED', rules: ['js-h1-modified'] },
  'contains-javascript-content': { status: 'COVERED', rules: ['js-rendered-content'] },
  'contains-javascript-links': { status: 'COVERED', rules: ['js-rendered-links'] },
};
